boxen:
  channel: '#boxen'
  repos:
    - boxen-web
    - our-boxen
  use_labels: true
  exclude_labels:
    - wip

customer-group:
  channel: '#customer-market-eng'
  repos:
    - docs
    - envato-cloud-management
    - handdrill
    - lua-deflector
    - market-dev-expectations
    - market-shopfront
    - marketplace
    - marketplace-puppet
    - shopfront-infrastructure
    - themeAudit
    - toolbox
    - webuild.envato.com
  use_labels: true
  exclude_labels:
    - wip

developers:
  channel: '#developers'
  repos:
    - front-end-coding-test

discovery:
  channel: '#conversion-help'
  repos:
    - discovery
    - solid_octane
    - solid_octane_service
    - dewey
    - discovery-scheduler
    - recommendation-api
    - api-gateway
    - build.envato.com
    - search_public_api
    - discovery_users
    - ami-builder
    - discovery-docker
  use_labels: true
  exclude_labels:
    - wip

infracoders:
  channel: '#infracoders'
  repos:
    - ops-coding-test
  use_labels: true
  exclude_labels:
    - wip

customer-group-leads:
  channel: '#customer-eng-leads'
  repos:
    - customer-group-leads

infrastructure:
  channel: '#infrastructure'
  github_team_names: ['Infrastructure']
  repos:
    - marketplace-aws
    - envato-cloud-management
    - envato-platform-infrastructure
    - platform-iam-configuration
  use_labels: true
  exclude_labels:
    - wip

q-branch:
  channel: '#q-branch'
  github_team_names: ['q-branch']
  repos:
    - ami-bakery
    - auth0
    - envato-platform-infrastructure
    - keymaker
    - platform-iam-configuration
    - the-oracle
    - q-branch
  use_labels: true
  exclude_labels:
    - wip

finance-dev:
  channel: '#finance-dev-prs'
  repos:
    - au-rwt-summaries-generator
    - finance-central
    - finance-dev
    - finance_infrastructure
    - elements-earnings
    - elements_earnings-client
    - et-elements-storefront-elements-earnings
    - et-elements-earnings-payables
    - et-recurly-subscriptions-elements-earnings
    - event_translator_toolkit
    - event-translator-template
    - irs-summaries-generator
    - irs-solicitations
    - knuckle_cluster
    - payables
    - payables-client
    - payoneer
    - recurly_subscription_service
    - sites-earnings
    - skrill-payment
    - tax-forms
    - tax-forms-client
    - tax_rates
    - tax_calculator
  use_labels: true
  exclude_labels:
    - wip
