boxen:
  channel: '#boxen'
  repos:
    - boxen-web
    - our-boxen
  use_labels: true
  exclude_labels:
    - wip

envato-market:
  channel: '#marketplacedev'
  repos:
    - docs
    - envato.com
    - front-end-coding-test
    - handdrill
    - market-dev-expectations
    - marketplace
    - new-coding-test
    - themeAudit
    - webuild.envato.com
  use_labels: true
  exclude_labels:
    - wip

discovery:
  channel: '#discovery-notify'
  repos:
    - discovery
    - solid_octane
    - solid_octane_service
    - dewey
    - discovery-scheduler
    - recommender-api
    - api-gateway
    - build.envato.com
    - search_public_api
    - discovery_users
    - ami-builder
    - discovery-docker
  use_labels: true
  exclude_labels:
    - wip

site-reliability:
  channel: '#customer-uptime'
  repos:
    - envato-cloud-management
    - lua-deflector
    - marketplace-ansible
    - marketplace-puppet
    - ops-coding-test
    - toolbox
  use_labels: true
  exclude_labels:
    - wip

customer-group-leads:
  channel: '#customer-eng-leads'
  repos:
    - customer-group-leads

infrastructure:
  channel: '#infrastructure'
  github_team_names: ['Infrastructure']
  repos:
    - marketplace-aws
    - envato-cloud-management
    - envato-platform-infrastructure
    - platform-iam-configuration
  use_labels: true
  exclude_labels:
    - wip
