boxen:
  channel: '#boxen'
  repos:
    - boxen-web
    - our-boxen
  use_labels: true
  exclude_labels:
    - wip

customer-group:
  channel: '#customer-market-eng'
  repos:
    - docs
    - envato-cloud-management
    - envato.com
    - handdrill
    - lua-deflector
    - market-dev-expectations
    - market-shopfront
    - marketplace
    - marketplace-puppet
    - shopfront-infrastructure
    - themeAudit
    - toolbox
    - webuild.envato.com
  use_labels: true
  exclude_labels:
    - wip

developers:
  channel: '#developers'
  repos:
    - front-end-coding-test

discovery:
  channel: '#conversion-help'
  repos:
    - discovery
    - solid_octane
    - solid_octane_service
    - dewey
    - discovery-scheduler
    - recommendation-api
    - api-gateway
    - build.envato.com
    - search_public_api
    - discovery_users
    - ami-builder
    - discovery-docker
  use_labels: true
  exclude_labels:
    - wip

infracoders:
  channel: '#infracoders'
  repos:
    - ops-coding-test
  use_labels: true
  exclude_labels:
    - wip

customer-group-leads:
  channel: '#customer-eng-leads'
  repos:
    - customer-group-leads

infrastructure:
  channel: '#infrastructure'
  github_team_names: ['Infrastructure']
  repos:
    - marketplace-aws
    - envato-cloud-management
    - envato-platform-infrastructure
    - platform-iam-configuration
  use_labels: true
  exclude_labels:
    - wip

identity:
  channel: '#identity-dev'
  repos:
    - identity
    - identity-infrastructure
    - identity-client
    - identity-admin
    - identity-team
    - sso-server
    - sso-client
    - sso-embedded
    - sso-js
    - area51-client
    - area51
    - area51-server-deprecated
  use_labels: true
  exclude_labels:
    - wip
