boxen:
  channel: '#boxen'
  repos:
    - boxen-web
    - our-boxen
  use_labels: true
  exclude_labels:
    - wip

envato-market:
  channel: '#marketplacedev'
  repos:
    - db_backup
    - docs
    - envato.com
    - front-end-coding-test
    - handdrill
    - market-dev-expectations
    - marketplace
    - marketplace-puppet
    - marketplace_debian_package_build_scripts
    - new-coding-test
    - our-boxen
    - sso-client
    - themeAudit
    - webuild.envato.com
  use_labels: true
  exclude_labels:
    - wip

discovery:
  channel: '#discovery-notify'
  repos:
    - discovery
    - solid_octane
    - solid_octane_service
    - dewey
    - discovery-scheduler
    - recommender-api
    - api-gateway
    - build.envato.com
    - search_public_api
    - discovery_users
    - ami-builder
    - discovery-docker
  use_labels: true
  exclude_labels:
    - wip

site-reliability:
  channel: '#mp-site-reliability'
  repos:
    - envato-cloud-management
    - lua-deflector
    - marketplace-ansible
    - marketplace-puppet
    - ops-coding-test
    - toolbox
  use_labels: true
  exclude_labels:
    - wip

market-financedev:
  channel: '#mp-financedev-prs'
  github_team_names: ['Finance']
  repos:
    - marketplace
    - moneybookers-support-app
    - double_entry
    - cqrs-service-template
    - cqrs-es-framework
    - event-store
  use_labels: true
  exclude_labels:
    - wip

customer-group-leads:
  channel: '#customer-eng-leads'
  repos:
    - customer-group-leads
