# Please insert new items alphabetically.

tribble:
  members:
    - Maxodactyl
    - caseprince
    - reshadbinharun
    - mwhearty
    - posulliv
    - anju-james

  channel:
    "#tribble-private"

  quotes:
    - ":wave:"

spock:
  members:
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

jackalope:
  members:
    - mrk252
    - JDark-GrabCAD
    - GeorgeSheppard
    - vtravieso
    - RobertMJ
    - atardugno
    - kostiantynkolesnik

  channel:
    "#jackalope"
    
ibex:
  members:
    - NabilStratasys
    - robert-may1
    - alexmcarthur
  
  channel:
    "#ibex"

kirin:
  members:
    - jaySSYS
    - jeremyhovis
    - erikheide
    - deyaoren
    - renatarz
    - rossstanton
    - ThomasBeckerStratasys
    - tomstudanski
    - mklchum

  channel:
    "#kirin-notifications"

saya:
  members:
    - yosefm
    - DanMaltaStratasys 
    - ShaiWaiselStratasys 
    - shailipo
  
  channel: "#saya"
