# Please insert new items alphabetically.

tribble:
  members:
    - Maxodactyl
    - caseprince
    - reshadbinharun
    - mwhearty
    - posulliv
    - anju-james

  channel:
    "#tribble-private"

  quotes:
    - ":wave:"

spock:
  members:
    - johannessiig
    - tambet
  channel:
    "#spock-notifications"

jackalope:
  members:
    - dangrabcad
    - JDark-GrabCAD
    - GeorgeSheppard
    - RobertMJ

  channel:
    "#jackalope-private"

babel:
  members:
    - vtravieso
    - atardugno
    
  channel:
    "#babel"
    
ibex:
  members:
    - NabilStratasys
    - robert-may1
    - alexmcarthur
  
  channel:
    "#ibex"

kirin:
  members:
    - jaySSYS
    - jeremyhovis
    - erikheide
    - deyaoren
    - renatarz
    - rossstanton
    - ThomasBeckerStratasys
    - tomstudanski
    - mklchum

  channel:
    "#kirin-notifications"
